# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extended_inherited_resources}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["josevalim", "stevo"]
  s.date = %q{2010-04-22}
  s.description = %q{}
  s.email = %q{b.kosmowski@selleo.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "extended_inherited_resources.gemspec",
     "init.rb",
     "lib/inherited_resources.rb",
     "lib/inherited_resources/actions.rb",
     "lib/inherited_resources/base.rb",
     "lib/inherited_resources/base_helpers.rb",
     "lib/inherited_resources/belongs_to_helpers.rb",
     "lib/inherited_resources/blank_slate.rb",
     "lib/inherited_resources/class_methods.rb",
     "lib/inherited_resources/dsl.rb",
     "lib/inherited_resources/legacy/respond_to.rb",
     "lib/inherited_resources/legacy/responder.rb",
     "lib/inherited_resources/locales/en.yml",
     "lib/inherited_resources/polymorphic_helpers.rb",
     "lib/inherited_resources/responder.rb",
     "lib/inherited_resources/singleton_helpers.rb",
     "lib/inherited_resources/url_helpers.rb",
     "lib/inherited_resources/version.rb",
     "test/helper.rb",
     "test/test_extended_inherited_resources.rb"
  ]
  s.homepage = %q{http://github.com/stevo/extended_inherited_resources}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Slightly extended version of josevalim inherited_resources - for rails 2.3}
  s.test_files = [
    "test/helper.rb",
     "test/test_extended_inherited_resources.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

